### ISSUE TITLE
On at least Fedora 41, test_proc_fd_count_runsinglethread fails

### ISSUE THREAD

**Issue by musicinmybrain** [eminence/procfs#322]
On Fedora 41, using a fresh checkout of `v0.17.0`:

```
$ uname -srvmo
Linux 6.11.7-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov  8 19:23:10 UTC 2024 x86_64 GNU/Linux
$ RUST_BACKTRACE=1 cargo test
[…]
failures:

---- process::tests::test_proc_fd_count_runsinglethread stdout ----
thread 'process::tests::test_proc_fd_count_runsinglethread' panicked at procfs/src/process/tests.rs:355:5:
assertion `left == right` failed: opened two files and expected 25 open fds, saw 23
  left: 25
 right: 23
stack backtrace:
   0: rust_begin_unwind
             at /builddir/build/BUILD/rust-1.83.0-build/rustc-1.83.0-src/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /builddir/build/BUILD/rust-1.83.0-build/rustc-1.83.0-src/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /builddir/build/BUILD/rust-1.83.0-build/rustc-1.83.0-src/library/core/src/panicking.rs:367:5
   4: procfs::process::tests::test_proc_fd_count_runsinglethread
             at ./src/process/tests.rs:355:5
   5: procfs::process::tests::test_proc_fd_count_runsinglethread::{{closure}}
             at ./src/process/tests.rs:345:40
   6: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rust-1.83.0-build/rustc-1.83.0-src/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rust-1.83.0-build/rustc-1.83.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    process::tests::test_proc_fd_count_runsinglethread

test result: FAILED. 97 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.15s
```

**Comment by musicinmybrain** [comment]
I originally saw this while working on an update for the [`rust-procfs` package in Fedora](https://src.fedoraproject.org/rpms/rust-procfs).

**Comment by eminence** [comment]
Cargo test will, by default, run multiple tests at once (in multiple threads in the same process).

This causes problems for this test.  If you look in our [CI](https://github.com/eminence/procfs/blob/2f7889bf86a6f1026398431a505e236fe2ff0064/.github/workflows/rust.yml#L30-L32) workflow, you'll see this:

```yaml
    - name: Run tests
      run: cargo +${{ matrix.toolchain }} test --workspace --all-features --verbose -- --skip _runsinglethread
    - name: Run tests (single-threaded tests)
      run: cargo +${{ matrix.toolchain }} test --workspace --all-features --verbose -- _runsinglethread --test-threads 1
```


So we first run all tests **except** the tests except this `runsinglethread` test, and then we run the `runsinglethread` test, but with `--test-threads 1`
